name: Auto Label Issues

# 触发条件：当有新 Issue 被创建时
on:
  issues:
    types: [opened]

jobs:
  label-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Auto Label Issues
        id: auto-label
        uses: actions/github-script@v6
        with:
          script: |
            const issueTitle = context.payload.issue.title.toLowerCase();
            const issueBody = context.payload.issue.body.toLowerCase();
            const labelsToAdd = [];

            // 定义关键字和对应的标签
            const keywordsToLabels = {
              'bug': 'bug',
              'feature': 'enhancement',
              'documentation': 'documentation',
              'help': 'help wanted',
              'question': 'question'
            };

            // 根据关键字匹配标签
            for (const [keyword, label] of Object.entries(keywordsToLabels)) {
              if (issueTitle.includes(keyword) || issueBody.includes(keyword)) {
                labelsToAdd.push(label);
              }
            }

            // 添加匹配的标签
            if (labelsToAdd.length > 0) {
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: labelsToAdd
              });
            }
